
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asuka-PC
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panjang = new javax.swing.JTextField();
        lebar = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        volumebalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sisi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        volumekubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jarijari = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        volumebola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Program Perhitungan Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 220, 15);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel1.setLayout(null);
        jPanel1.add(panjang);
        panjang.setBounds(100, 20, 90, 30);
        jPanel1.add(lebar);
        lebar.setBounds(100, 60, 90, 30);
        jPanel1.add(tinggi);
        tinggi.setBounds(100, 100, 90, 30);

        jLabel2.setText("Panjang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(39, 30, 60, 14);

        jLabel3.setText("Lebar");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 70, 60, 14);

        jLabel4.setText("Tinggi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(38, 110, 50, 14);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 110, 34, 14);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 30, 34, 14);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 70, 34, 14);

        volumebalok.setText("Volume");
        volumebalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumebalokActionPerformed(evt);
            }
        });
        jPanel1.add(volumebalok);
        volumebalok.setBounds(40, 150, 67, 23);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(39, 30, 60, 14);
        jPanel2.add(sisi);
        sisi.setBounds(100, 20, 90, 30);

        jLabel11.setText("cm");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(200, 30, 34, 14);

        volumekubus.setText("Volume");
        volumekubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumekubusActionPerformed(evt);
            }
        });
        jPanel2.add(volumekubus);
        volumekubus.setBounds(40, 150, 67, 23);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel14.setText("Jari-jari");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(39, 30, 60, 14);
        jPanel3.add(jarijari);
        jarijari.setBounds(100, 20, 90, 30);

        jLabel17.setText("cm");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(200, 30, 34, 14);

        volumebola.setText("Volume");
        volumebola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumebolaActionPerformed(evt);
            }
        });
        jPanel3.add(volumebola);
        volumebola.setBounds(40, 150, 67, 23);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(-5, 60, 410, 240);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void volumebalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumebalokActionPerformed
        // TODO add your handling code here:
        int Panjang, Lebar, Tinggi;
        Panjang = Integer.parseInt(panjang.getText());
        Lebar = Integer.parseInt(lebar.getText());
        Tinggi = Integer.parseInt(tinggi.getText());
        int hasil = Panjang*Lebar*Tinggi;
        
        try{
            JOptionPane.showMessageDialog(null, "Volume Balok adalah :"+hasil, "volume", JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_volumebalokActionPerformed

    private void volumekubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumekubusActionPerformed
        // TODO add your handling code here:
        int Sisi;
        Sisi = Integer.parseInt(sisi.getText());
        int hasil = Sisi*Sisi*Sisi;
        
        try{
            JOptionPane.showMessageDialog(null, "Volume Kubus adalah :"+hasil, "volume", JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_volumekubusActionPerformed

    private void volumebolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumebolaActionPerformed
        // TODO add your handling code here:
        float Jarijari;
        Jarijari = Integer.parseInt(jarijari.getText());
        float hasil = (float) ((4*Math.PI*Jarijari*Jarijari*Jarijari)/3);
        
        try{
            JOptionPane.showMessageDialog(null, "Volume Bola adalah :"+hasil, "volume", JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_volumebolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jarijari;
    private javax.swing.JTextField lebar;
    private javax.swing.JTextField panjang;
    private javax.swing.JTextField sisi;
    private javax.swing.JTextField tinggi;
    private javax.swing.JButton volumebalok;
    private javax.swing.JButton volumebola;
    private javax.swing.JButton volumekubus;
    // End of variables declaration//GEN-END:variables
}
